{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['year', 'month', 'period', 'type', 'code', 'active'],
    merge_update_columns=[
        'capex_revenue', 'capital', 'changed_at', 'current_ratio', 'debt_equity', 'debt_ratio',
        'debtebitda', 'dpr', 'ebitda_margin', 'ev_ebit', 'evebitda', 'evs', 'exchange', 'gross_margin',
        'interest_coverage', 'net_margin', 'net_working_capital', 'netdebt_ebitda', 'operation_margin',
        'pbv', 'pcf', 'pe', 'pfcf', 'pffo', 'ps', 'roa', 'roce', 'roe', 'roic', 'ros']
  )
}}
SELECT
    year::bigint "year",
    month::bigint "month",
    UPPER(period) period,
    UPPER(type) "type",
    UPPER(code) code,
    active::boolean active,
    capex_revenue,
    capital,
    changed_at,
    current_ratio,
    debt_equity,
    debt_ratio,
    debtebitda,
    dpr,
    ebitda_margin,
    ev_ebit,
    evebitda,
    evs,
    exchange,
    gross_margin,
    interest_coverage,
    net_margin,
    net_working_capital,
    netdebt_ebitda,
    operation_margin,
    pbv,
    pcf,
    pe,
    pfcf,
    pffo,
    ps,
    roa,
    roce,
    roe,
    roic,
    ros
FROM {{ ref('stg_fm_ratios') }}
