{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key=['exchange', 'code', 'type', 'period', 'year', 'month'],
    merge_update_columns=['active', 'capex_revenue', 'capital', 'changed_at', 'current_ratio', 'debt_equity',
    'debt_ratio', 'debtebitda', 'dpr', 'ebitda_margin', 'ev_ebit', 'evebitda', 'evs', 'gross_margin',
    'interest_coverage', 'net_margin', 'net_working_capital', 'netdebt_ebitda', 'operation_margin',
    'pbv', 'pcf', 'pe', 'pfcf', 'pffo', 'ps', 'roa', 'roce', 'roe', 'roic', 'ros']

  )
}}
SELECT DISTINCT
    active,
    capex_revenue,
    capital,
    CAST(changed_at AS TIMESTAMP) AS changed_at,
    code,
    current_ratio,
    debt_equity,
    debt_ratio,
    debtebitda,
    dpr,
    ebitda_margin,
    ev_ebit,
    evebitda,
    evs,
    exchange,
    gross_margin,
    interest_coverage,
    "month",
    net_margin,
    net_working_capital,
    netdebt_ebitda,
    operation_margin,
    pbv,
    pcf,
    pe,
    period,
    pfcf,
    pffo,
    ps,
    roa,
    roce,
    roe,
    roic,
    ros,
    type,
    "year"
FROM {{ ref('stg_ratios') }}