version: 2

models:
  - name: dim_emitents
    description: "Dimension table of russian emitents"
    constraints:
      - type: primary_key
        columns: ['id_emitent', 'inn']
    config:
      materialized: table
      tags: [ 'sql' ]
  - name: dim_girbo_organizations_cards
    description: "Dimension table of cards (ids) for search queries on https://bo.nalog.ru/query=<inn>"
    columns:
      - name: inn
        description: "INN of organization"
      - name: card
        description: "Card of organization search queries"
    constraints:
      - type: primary_key
        columns: [ "inn" ]
      - type: unique
        columns: [ "card" ]
  - name: dim_moex_boards
    description: "Dimension table of moex boards"
    columns:
      - name: id
        description: "id of board from moex"
      - name: board_group_id
      - name: boardid
        description: "Unique code of a board"
      - name: title
        description: "Name of board"
      - name: is_traded
    constraints:
      - type: primary_key
        columns: 'id'
    config:
      materialized: table
      tags: [ 'sql' ]
  - name: dim_moex_securitites
    description: "Dimension table of securities on MOEX"
    columns:
      - name: id
      - name: secid
      - name: shortname
      - name: regnumber
      - name: name
      - name: isin
      - name: is_traded
      - name: id_emitent
      - name: inn
      - name: type
      - name: grp
      - name: boardid
    constraints:
      - type: primary_key
        columns: ['secid', 'boardid']
    config:
      materialized: table
      tags: [ 'sql' ]
  - name: dim_moex_securitites_trading
    description: "Dimension table of securities actively traded on MOEX"
    columns:
      - name: id
      - name: secid
      - name: shortname
      - name: regnumber
      - name: name
      - name: isin
      - name: is_traded
      - name: id_emitent
      - name: inn
      - name: type
      - name: grp
      - name: boardid
    constraints:
      - type: primary_key
        columns: ['secid', 'boardid']
    config:
      materialized: table
      tags: [ 'sql' ]
  - name: fct_fundamentals
    description: "Table of fundamentals of russian companies from https://bo.nalog.ru/"
    columns:
      - name: inn
        description: "INN of organization"
      - name: year
        description: "year of reporting"
    constraints:
      - type: primary_key
        columns: [ "inn", "year" ]
  - name: fct_moex_prices
    description: "Fact table of prices from moex"
    columns:
      - name: boardid
      - name: tradedate
      - name: secid
      - name: numtrades
      - name: value
      - name: open
      - name: low
      - name: high
      - name: legalcloseprice
      - name: waprice
      - name: close
      - name: volume
      - name: marketprice2
      - name: marketprice3
      - name: admittedquote
      - name: mp2valtrd
      - name: marketprice3tradesvalue
      - name: admittedvalue
      - name: waval
      - name: tradingsession
      - name: trendclspr
    constraints:
      - type: primary_key
        columns: ['secid', 'boardid', 'tradedate']
    config:
      materialized: table
      tags: [ 'sql' ]
