CREATE VIEW v_ratios AS
WITH ratios_year AS (
	SELECT *
	FROM ratios
	WHERE period = 'Y'
)
, generated_years AS (
    SELECT
        code,
        type,
        arrayJoin(range(min_year, toYear(current_date()) + 1)) AS year
    FROM (
        SELECT
            code, type, MIN(year) AS min_year
        FROM ratios_year
        GROUP BY code, type
    )
)
, ratios_argmax AS (
    SELECT
        g.code AS code,
        g."year" AS "year",
        g.type AS type,
        argMax(r.active, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS active,
        argMax(r.capex_revenue, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS capex_revenue,
        argMax(r.capital, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS capital,
        argMax(r.changed_at, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS changed_at,
        argMax(r.current_ratio, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS current_ratio,
        argMax(r.debt_equity, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS debt_equity,
        argMax(r.debt_ratio, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS debt_ratio,
        argMax(r.debtebitda, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS debtebitda,
        argMax(r.dpr, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS dpr,
        argMax(r.ebitda_margin, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS ebitda_margin,
        argMax(r.ev_ebit, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS ev_ebit,
        argMax(r.evebitda, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS evebitda,
        argMax(r.evs, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS evs,
        argMax(r.exchange, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS exchange,
        argMax(r.gross_margin, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS gross_margin,
        argMax(r.interest_coverage, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS interest_coverage,
        argMax(r."month", g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS "month",
        argMax(r.net_margin, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS net_margin,
        argMax(r.net_working_capital, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS net_working_capital,
        argMax(r.netdebt_ebitda, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS netdebt_ebitda,
        argMax(r.operation_margin, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS operation_margin,
        argMax(r.pbv, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS pbv,
        argMax(r.pcf, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS pcf,
        argMax(r.pe, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS pe,
        argMax(r.pfcf, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS pfcf,
        argMax(r.pffo, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS pffo,
        argMax(r.ps, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS ps,
        argMax(r.roa, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS roa,
        argMax(r.roce, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS roce,
        argMax(r.roe, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS roe,
        argMax(r.roic, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS roic,
        argMax(r.ros, g."year") OVER (PARTITION BY g.code, g.type ORDER BY g."year") AS ros
    FROM generated_years AS g
    LEFT JOIN ratios_year AS r
        ON g.code = r.code AND g.type = r.type AND g.year = r.year
    SETTINGS join_use_nulls = 1
)
, ratios_pivot AS (
    SELECT
        exchange,
        code,
        "year",
        Max(if(type='МСФО', active, NULL)) AS active_msfo,
        Max(if(type='РСБУ', active, NULL)) AS active_rsbu,
        Max(if(type='МСФО', capex_revenue, NULL)) AS capex_revenue_msfo,
        Max(if(type='РСБУ', capex_revenue, NULL)) AS capex_revenue_rsbu,
        Max(if(type='МСФО', capital, NULL)) AS capital_msfo,
        Max(if(type='РСБУ', capital, NULL)) AS capital_rsbu,
        Max(if(type='МСФО', current_ratio, NULL)) AS current_ratio_msfo,
        Max(if(type='РСБУ', current_ratio, NULL)) AS current_ratio_rsbu,
        Max(if(type='МСФО', debt_equity, NULL)) AS debt_equity_msfo,
        Max(if(type='РСБУ', debt_equity, NULL)) AS debt_equity_rsbu,
        Max(if(type='МСФО', debt_ratio, NULL)) AS debt_ratio_msfo,
        Max(if(type='РСБУ', debt_ratio, NULL)) AS debt_ratio_rsbu,
        Max(if(type='МСФО', debtebitda, NULL)) AS debtebitda_msfo,
        Max(if(type='РСБУ', debtebitda, NULL)) AS debtebitda_rsbu,
        Max(if(type='МСФО', dpr, NULL)) AS dpr_msfo,
        Max(if(type='РСБУ', dpr, NULL)) AS dpr_rsbu,
        Max(if(type='МСФО', ebitda_margin, NULL)) AS ebitda_margin_msfo,
        Max(if(type='РСБУ', ebitda_margin, NULL)) AS ebitda_margin_rsbu,
        Max(if(type='МСФО', ev_ebit, NULL)) AS ev_ebit_msfo,
        Max(if(type='РСБУ', ev_ebit, NULL)) AS ev_ebit_rsbu,
        Max(if(type='МСФО', evebitda, NULL)) AS evebitda_msfo,
        Max(if(type='РСБУ', evebitda, NULL)) AS evebitda_rsbu,
        Max(if(type='МСФО', evs, NULL)) AS evs_msfo,
        Max(if(type='РСБУ', evs, NULL)) AS evs_rsbu,
        Max(if(type='МСФО', gross_margin, NULL)) AS gross_margin_msfo,
        Max(if(type='РСБУ', gross_margin, NULL)) AS gross_margin_rsbu,
        Max(if(type='МСФО', interest_coverage, NULL)) AS interest_coverage_msfo,
        Max(if(type='РСБУ', interest_coverage, NULL)) AS interest_coverage_rsbu,
        Max(if(type='МСФО', net_margin, NULL)) AS net_margin_msfo,
        Max(if(type='РСБУ', net_margin, NULL)) AS net_margin_rsbu,
        Max(if(type='МСФО', net_working_capital, NULL)) AS net_working_capital_msfo,
        Max(if(type='РСБУ', net_working_capital, NULL)) AS net_working_capital_rsbu,
        Max(if(type='МСФО', netdebt_ebitda, NULL)) AS netdebt_ebitda_msfo,
        Max(if(type='РСБУ', netdebt_ebitda, NULL)) AS netdebt_ebitda_rsbu,
        Max(if(type='МСФО', operation_margin, NULL)) AS operation_margin_msfo,
        Max(if(type='РСБУ', operation_margin, NULL)) AS operation_margin_rsbu,
        Max(if(type='МСФО', pbv, NULL)) AS pbv_msfo,
        Max(if(type='РСБУ', pbv, NULL)) AS pbv_rsbu,
        Max(if(type='МСФО', pcf, NULL)) AS pcf_msfo,
        Max(if(type='РСБУ', pcf, NULL)) AS pcf_rsbu,
        Max(if(type='МСФО', pe, NULL)) AS pe_msfo,
        Max(if(type='РСБУ', pe, NULL)) AS pe_rsbu,
        Max(if(type='МСФО', pfcf, NULL)) AS pfcf_msfo,
        Max(if(type='РСБУ', pfcf, NULL)) AS pfcf_rsbu,
        Max(if(type='МСФО', pffo, NULL)) AS pffo_msfo,
        Max(if(type='РСБУ', pffo, NULL)) AS pffo_rsbu,
        Max(if(type='МСФО', ps, NULL)) AS ps_msfo,
        Max(if(type='РСБУ', ps, NULL)) AS ps_rsbu,
        Max(if(type='МСФО', roa, NULL)) AS roa_msfo,
        Max(if(type='РСБУ', roa, NULL)) AS roa_rsbu,
        Max(if(type='МСФО', roce, NULL)) AS roce_msfo,
        Max(if(type='РСБУ', roce, NULL)) AS roce_rsbu,
        Max(if(type='МСФО', roe, NULL)) AS roe_msfo,
        Max(if(type='РСБУ', roe, NULL)) AS roe_rsbu,
        Max(if(type='МСФО', roic, NULL)) AS roic_msfo,
        Max(if(type='РСБУ', roic, NULL)) AS roic_rsbu,
        Max(if(type='МСФО', ros, NULL)) AS ros_msfo,
        Max(if(type='РСБУ', ros, NULL)) AS ros_rsbu
    FROM ratios_argmax
    GROUP BY
        exchange,
        code,
        "year"
)
, sec AS (
	SELECT secid, inn
	FROM (
		SELECT secid, inn,
			row_number() OVER (PARTITION BY secid ORDER BY settledate) rn
		FROM v_moex_securities
	)
	WHERE rn = 1
)
SELECT
	r.exchange,
    r.code AS code,
    r."year" AS "year",
    r.active_msfo AS active_msfo,
    r.active_rsbu AS active_rsbu,
    r.capex_revenue_msfo AS capex_revenue_msfo,
    r.capex_revenue_rsbu AS capex_revenue_rsbu,
    r.capital_msfo AS capital_msfo,
    r.capital_rsbu AS capital_rsbu,
    r.current_ratio_msfo AS current_ratio_msfo,
    r.current_ratio_rsbu AS current_ratio_rsbu,
    r.debt_equity_msfo AS debt_equity_msfo,
    r.debt_equity_rsbu AS debt_equity_rsbu,
    r.debt_ratio_msfo AS debt_ratio_msfo,
    r.debt_ratio_rsbu AS debt_ratio_rsbu,
    r.debtebitda_msfo AS debt_ebitda_msfo,
    r.debtebitda_rsbu AS debt_ebitda_rsbu,
    r.dpr_msfo AS dpr_msfo,
    r.dpr_rsbu AS dpr_rsbu,
    r.ebitda_margin_msfo AS ebitda_margin_msfo,
    r.ebitda_margin_rsbu AS ebitda_margin_rsbu,
    r.ev_ebit_msfo AS ev_ebit_msfo,
    r.ev_ebit_rsbu AS ev_ebit_rsbu,
    r.evebitda_msfo AS ev_ebitda_msfo,
    r.evebitda_rsbu AS ev_ebitda_rsbu,
    r.evs_msfo AS evs_msfo,
    r.evs_rsbu AS evs_rsbu,
    r.gross_margin_msfo AS gross_margin_msfo,
    r.gross_margin_rsbu AS gross_margin_rsbu,
    r.interest_coverage_msfo AS interest_coverage_msfo,
    r.interest_coverage_rsbu AS interest_coverage_rsbu,
    r.net_margin_msfo AS net_margin_msfo,
    r.net_margin_rsbu AS net_margin_rsbu,
    r.net_working_capital_msfo AS net_working_capital_msfo,
    r.net_working_capital_rsbu AS net_working_capital_rsbu,
    r.netdebt_ebitda_msfo AS net_debt_ebitda_msfo,
    r.netdebt_ebitda_rsbu AS net_debt_ebitda_rsbu,
    r.operation_margin_msfo AS operation_margin_msfo,
    r.operation_margin_rsbu AS operation_margin_rsbu,
    r.pbv_msfo AS pbv_msfo,
    r.pbv_rsbu AS pbv_rsbu,
    r.pcf_msfo AS pcf_msfo,
    r.pcf_rsbu AS pcf_rsbu,
    r.pe_msfo AS pe_msfo,
    r.pe_rsbu AS pe_rsbu,
    r.pfcf_msfo AS pfcf_msfo,
    r.pfcf_rsbu AS pfcf_rsbu,
    r.pffo_msfo AS pffo_msfo,
    r.pffo_rsbu AS pffo_rsbu,
    r.ps_msfo AS ps_msfo,
    r.ps_rsbu AS ps_rsbu,
    r.roa_msfo AS roa_msfo,
    r.roa_rsbu AS roa_rsbu,
    r.roce_msfo AS roce_msfo,
    r.roce_rsbu AS roce_rsbu,
    r.roe_msfo AS roe_msfo,
    r.roe_rsbu AS roe_rsbu,
    r.roic_msfo AS roic_msfo,
    r.roic_rsbu AS roic_rsbu,
    r.ros_msfo AS ros_msfo,
    r.ros_rsbu AS ros_rsbu,
    sec.inn AS inn,
    f."1100" AS "1100",
    f."1110" AS "1110",
    f."1120" AS "1120",
    f."1130" AS "1130",
    f."1140" AS "1140",
    f."1150" AS "1150",
    f."1160" AS "1160",
    f."1170" AS "1170",
    f."1180" AS "1180",
    f."1190" AS "1190",
    f."1200" AS "1200",
    f."1210" AS "1210",
    f."1220" AS "1220",
    f."1230" AS "1230",
    f."1240" AS "1240",
    f."1250" AS "1250",
    f."1260" AS "1260",
    f."1300" AS "1300",
    f."1310" AS "1310",
    f."1320" AS "1320",
    f."1340" AS "1340",
    f."1350" AS "1350",
    f."1360" AS "1360",
    f."1370" AS "1370",
    f."1400" AS "1400",
    f."1410" AS "1410",
    f."1420" AS "1420",
    f."1430" AS "1430",
    f."1450" AS "1450",
    f."1500" AS "1500",
    f."1510" AS "1510",
    f."1520" AS "1520",
    f."1530" AS "1530",
    f."1540" AS "1540",
    f."1550" AS "1550",
    f."1600" AS "1600",
    f."1700" AS "1700",
    f."2100" AS "2100",
    f."2110" AS "2110",
    f."2120" AS "2120",
    f."2200" AS "2200",
    f."2210" AS "2210",
    f."2220" AS "2220",
    f."2300" AS "2300",
    f."2310" AS "2310",
    f."2320" AS "2320",
    f."2330" AS "2330",
    f."2340" AS "2340",
    f."2350" AS "2350",
    f."2400" AS "2400",
    f."2410" AS "2410",
    f."2421" AS "2421",
    f."2430" AS "2430",
    f."2450" AS "2450",
    f."2460" AS "2460",
    f."2500" AS "2500",
    f."2510" AS "2510",
    f."2520" AS "2520",
    f."3200" AS "3200",
    f."3300" AS "3300",
    f."3310" AS "3310",
    f."3311" AS "3311",
    f."3312" AS "3312",
    f."3313" AS "3313",
    f."3314" AS "3314",
    f."3315" AS "3315",
    f."3316" AS "3316",
    f."3320" AS "3320",
    f."3321" AS "3321",
    f."3322" AS "3322",
    f."3323" AS "3323",
    f."3324" AS "3324",
    f."3325" AS "3325",
    f."3326" AS "3326",
    f."3327" AS "3327",
    f."3330" AS "3330",
    f."3340" AS "3340",
    f."3600" AS "3600",
    f."4100" AS "4100",
    f."4110" AS "4110",
    f."4111" AS "4111",
    f."4112" AS "4112",
    f."4113" AS "4113",
    f."4119" AS "4119",
    f."4120" AS "4120",
    f."4121" AS "4121",
    f."4122" AS "4122",
    f."4123" AS "4123",
    f."4124" AS "4124",
    f."4129" AS "4129",
    f."4200" AS "4200",
    f."4210" AS "4210",
    f."4211" AS "4211",
    f."4212" AS "4212",
    f."4213" AS "4213",
    f."4214" AS "4214",
    f."4219" AS "4219",
    f."4220" AS "4220",
    f."4221" AS "4221",
    f."4222" AS "4222",
    f."4223" AS "4223",
    f."4224" AS "4224",
    f."4229" AS "4229",
    f."4300" AS "4300",
    f."4310" AS "4310",
    f."4311" AS "4311",
    f."4312" AS "4312",
    f."4313" AS "4313",
    f."4314" AS "4314",
    f."4319" AS "4319",
    f."4320" AS "4320",
    f."4321" AS "4321",
    f."4322" AS "4322",
    f."4323" AS "4323",
    f."4329" AS "4329",
    f."4400" AS "4400",
    f."4490" AS "4490",
    f."6100" AS "6100",
    f."6200" AS "6200",
    f."6210" AS "6210",
    f."6215" AS "6215",
    f."6220" AS "6220",
    f."6230" AS "6230",
    f."6240" AS "6240",
    f."6250" AS "6250",
    f."6300" AS "6300",
    f."6310" AS "6310",
    f."6311" AS "6311",
    f."6312" AS "6312",
    f."6313" AS "6313",
    f."6320" AS "6320",
    f."6321" AS "6321",
    f."6322" AS "6322",
    f."6323" AS "6323",
    f."6324" AS "6324",
    f."6325" AS "6325",
    f."6326" AS "6326",
    f."6330" AS "6330",
    f."6350" AS "6350",
    f."6400" AS "6400",
    f."2411" AS "2411",
    f."4450" AS "4450",
    f."4500" AS "4500",
    f."2412" AS "2412",
    f."3100" AS "3100",
    f."3210" AS "3210",
    f."3211" AS "3211",
    f."3230" AS "3230",
    f."3400" AS "3400",
    f."3401" AS "3401",
    f."3402" AS "3402",
    f."3500" AS "3500",
    f."3501" AS "3501",
    f."3502" AS "3502",
    f."3220" AS "3220",
    f."3221" AS "3221",
    f."3410" AS "3410",
    f."3411" AS "3411",
    f."2900" AS "2900",
    f."2910" AS "2910",
    f."3213" AS "3213",
    f."3227" AS "3227",
    f."3223" AS "3223",
    f."3420" AS "3420",
    f."3421" AS "3421",
    f."3240" AS "3240",
    f."3212" AS "3212",
    f."3222" AS "3222",
    f."2530" AS "2530",
    f."3216" AS "3216",
    f."3226" AS "3226",
    f."3214" AS "3214",
    f."3215" AS "3215",
    f."3224" AS "3224",
    f."3225" AS "3225",
    f."3412" AS "3412",
    f."3422" AS "3422"
FROM ratios_pivot AS r
LEFT JOIN sec ON sec.secid = r.code
LEFT JOIN v_fundamentals f ON f.inn = sec.inn AND r."year" = f."year"
SETTINGS join_use_nulls = 1
