version: 2

models:
  - name: stg_girbo_fundamentals
    config:
      materialized: view
  - name: stg_moex_boards
    columns:
      - name: id
      - name: board_group_id
      - name: boardid
      - name: title
      - name: is_traded
    config:
      materialized: view
  - name: stg_moex_companies
    config:
      materialized: view
  - name: stg_moex_shares
    config:
      materialized: view
  - name: stg_moex_prices
    columns:
      - name: boardid
      - name: tradedate
      - name: shortname
      - name: secid
      - name: numtrades
      - name: value
      - name: open
      - name: low
      - name: high
      - name: legalcloseprice
      - name: waprice
      - name: close
      - name: volume
      - name: marketprice2
      - name: marketprice3
      - name: admittedquote
      - name: mp2valtrd
      - name: marketprice3tradesvalue
      - name: admittedvalue
      - name: waval
      - name: tradingsession
      - name: currencyid
      - name: trendclspr
      - name: trade_session_date
    config:
      materialized: view
#  - name: stg_rudata_emitents
#    config:
#      materialized: view

sources:
  - name: moex
    database: invest
    schema: moex
    tables:
      - name: Companies
      - name: HistoryStockSharesSecurities
      - name: StockSharesBoards
      - name: StockSharesSecurities
      - name: StockSharesSecuritiesMarketData
#  - name: rudata
#    database: invest
#    schema: rudata
#    tables:
#      - name: api_rudata_emitents
  - name: girbo
    database: invest
    schema: girbo
    tables:
      - name: fundamentals
  - name: tbank
    database: invest
    schema: tbank
    tables:
      - name: bonds
      - name: etfs
      - name: shares
      - name: historic_candles1
  - name: finance_marker
    database: invest
    schema: finance_marker
    tables:
      - name: ratios
  - name: cbr
    database: invest
    schema: cbr
    tables:
      - name: KeyRate
      - name: GetCursOnDate
      - name: DragMetDynamic
      - name: Ruonia
