version: 2

models:
  - name: stg_moex_boards
    columns:
      - name: id
      - name: board_group_id
      - name: boardid
      - name: title
      - name: is_traded
      - name: load_ts
    config:
      materialized: view
  - name: stg_moex_shares
    config:
      materialized: view
  - name: stg_moex_prices
    columns:
      - name: boardid
      - name: tradedate
      - name: shortname
      - name: secid
      - name: numtrades
      - name: value
      - name: open
      - name: low
      - name: high
      - name: legalcloseprice
      - name: waprice
      - name: close
      - name: volume
      - name: marketprice2
      - name: marketprice3
      - name: admittedquote
      - name: mp2valtrd
      - name: marketprice3tradesvalue
      - name: admittedvalue
      - name: waval
      - name: tradingsession
      - name: currencyid
      - name: trendclspr
      - name: trade_session_date
      - name: load_ts
    config:
      materialized: view
  - name: stg_rudata_emitents
    config:
      materialized: view

sources:
  - name: moex
    database: invest
    schema: public
    tables:
      - name: api_moex_boards
      - name: api_moex_shares
      - name: api_moex_prices
  - name: rudata
    database: invest
    schema: public
    tables:
      - name: api_rudata_emitents
  - name: girbo
    database: invest
    schema: public
    tables:
      - name: api_girbo_fundamentals